/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gennis.vagas;

/**
 *
 * @author ADMIN
 */
public class TelaMapaVagas extends javax.swing.JFrame {

    /**
     * Creates new form TelaMapaVagas
     */
    public TelaMapaVagas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBase = new javax.swing.JPanel();
        painelMenu = new javax.swing.JPanel();
        painelSub = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelBase.setBackground(new java.awt.Color(255, 255, 255));
        painelBase.setMaximumSize(new java.awt.Dimension(0, 0));
        painelBase.setMinimumSize(new java.awt.Dimension(0, 0));
        painelBase.setPreferredSize(new java.awt.Dimension(0, 0));
        painelBase.setLayout(new java.awt.BorderLayout());

        painelMenu.setOpaque(false);
        painelMenu.setLayout(new java.awt.GridLayout(0, 15, 3, 3));
        painelBase.add(painelMenu, java.awt.BorderLayout.CENTER);

        painelSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        painelSub.setOpaque(false);
        painelSub.setPreferredSize(new java.awt.Dimension(832, 70));

        javax.swing.GroupLayout painelSubLayout = new javax.swing.GroupLayout(painelSub);
        painelSub.setLayout(painelSubLayout);
        painelSubLayout.setHorizontalGroup(
            painelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        painelSubLayout.setVerticalGroup(
            painelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        painelBase.add(painelSub, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(painelBase, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMapaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMapaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMapaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMapaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMapaVagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelBase;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelSub;
    // End of variables declaration//GEN-END:variables
}
